blank_issues_enabled: false
contact_links:
  - name: Time Guardian Support
    url: mailto:timeguardianllc@gmail.com
    about: Please contact us directly for support questions or help with your account
